### ISSUE TITLE
OSError: SavedModel file does not exist at: model/yolov3-tiny.h5/{saved_model.pbtxt|saved_model.pb}

### ISSUE THREAD

**Issue by ghost** [wuhanstudio/adversarial-detection#2]
Hi - I get the error below when running python detect.py --model model/yolov3-tiny.h5 --class_name coco_classes.txt into a conda promp.

OSError: SavedModel file does not exist at: model/yolov3-tiny.h5/{saved_model.pbtxt|saved_model.pb}

There does not appear to be a yolov3-tiny.h5 file in the folder model. The folder is empty.

**Comment by wuhanstudio** [comment]
Hi,

The models are released here:

https://github.com/wuhanstudio/adversarial-detection/releases/tag/v1.0.0

I also updated the README. By default, YOLOv3-Tiny is used. Please remember to change the anchors if you would like to use YOLOv3.

YOLOv3-Tiny (default):

https://github.com/wuhanstudio/adversarial-detection/blob/b3a4d35777d54047f0bd56860bacb1d4a757a70a/detect.py#L142

YOLOv3:
```
boxes, class_ids, confidences = yolo_process_output(outs, yolov3_anchors, len(classes))
```

**Comment by ghost** [comment]
Thank you—resolved/closed the issue.
